#!/bin/sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

ENV_FILE="$ROOT_DIR/src/.env.local"

echo
echo "🔧 Setting up local environment..."
echo

# -----------------------------
# Certificate Check
# -----------------------------

CERT_DIR="$ROOT_DIR/certs"

if [ ! -d "$CERT_DIR" ] || [ -z "$(ls -A "$CERT_DIR")" ]; then
  echo "⚠️  Development certificates not found. Run scripts/dev-certs.sh to create them."
  echo
  exit 1
else
  echo "✅ Development certificates found."
  echo
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-env.sh
# Do not commit this file

CERT_DIR=$CERT_DIR

EOF